### PR TITLE
fix: Add optional to type chain

### LINKED ISSUE #559: Bug caused by missing PR Author
This bug occurs when trying to run a craft release workflow on a repo where PRs contain ghost users (deleted accounts). For example: https://github.com/getsentry/jsonnet-libs/pull/7

Normally, the release should run properly and should just skip & not include author names for the PRs which were opened by a deleted account. 

Instead, craft errors with the message `Error:  Cannot read properties of null (reading 'login')
  at /usr/local/bin/craft:399:261` due to the author fields missing from the graphql response and being null

### PR DESCRIPTION
**Pull request by brian-lou**
This PR fixes #559

### CODE REVIEW

File: src/utils/changelog.ts [hunk 1]
```diff
@@ -472,7 +472,7 @@ async function getPRAndMilestoneFromCommit(
         hash.slice(1),
         pr
           ? {
-              author: pr.author.login,
+              author: pr.author?.login ?? null,
```
Comment (asottile-sentry) [inline src/utils/changelog.ts:475]: I don't think `?? null` is needed here with the `?.` access (since that'll become `undefined` already) -- I think this also needs a fix to the types above because as it is right now the `?.` looks unnecessary (I'm surprised the type checker isn't complaining about this?)

**Review by asottile-sentry — COMMENTED** [review]
should probably also include a test -- here's the actual api body for the PR which may be helpful in crafting a fake graphql response for a test https://api.github.com/repos/getsentry/jsonnet-libs/pulls/5

**Review by asottile-sentry — APPROVED** [review]
please add the additional context to the issue as requested on slack -- looks good and thanks for the test! (helps to show that this makes a reasonable output too!)
