### PR TITLE
Publish to GitHub more atomically using draft repos

### LINKED ISSUE #336: Tag more carefully in GitHub target
Currently the GitHub target creates a tag fairly early in the process, which means that if something fails after it, the tag must be recreated. On https://github.com/getsentry/self-hosted/issues/1193 we observed a fairly drastic scenario where an overlarge changelog prevented creating a release object, and then a manual tag remove/add cascaded into a broken CI incident. Uploading artifacts to GitHub is another source of intermittent errors that can land us in a hanging tag state.

It seems from my reading of `createAnnotatedTag` that we need a tag kind of early in the process. Can we use a temporary tag and then set the final tag as the last step in the process?

What other ways could we solve this problem?

### PR DESCRIPTION
**Pull request by chadwhitacre**
Closes #336.

Tested with https://github.com/getsentry/testing-craft-chadwhitacre/blob/0.0.9/test.

E.g. https://github.com/getsentry/testing-craft-chadwhitacre/

------------

Screen Shot 2022-01-14 at 2 28 52 PM

------------

Screen Shot 2022-01-14 at 2 29 05 PM

### CODE REVIEW

**Comment by chadwhitacre** [comment]
cc: @BYK :)

**Comment by chadwhitacre** [comment]
As implemented, we always start a new draft with every `craft publish`, hence there is no more need to delete assets from a possibly already-existing release object. In the event of a failure the draft release will be left over and can be deleted manually.

File: src/targets/github.ts [hunk 1]
```diff
@@ -187,56 +130,25 @@ export class GithubTarget extends BaseTarget {
...
+        name: tag,
+        owner: this.githubConfig.owner,
+        prerelease: isPreview,
+        repo: this.githubConfig.repo,
+        tag_name: tag,
+        target_commitish: revision,
+        ...changes,
+      });
+      return created.data;
     }
```
Comment (kamilogorek) [inline src/targets/github.ts:152]:
```suggestion

    const created = await this.github.repos.createRelease({
      draft: true,
      name: tag,
      owner: this.githubConfig.owner,
      prerelease: isPreview,
      repo: this.githubConfig.repo,
      tag_name: tag,
      target_commitish: revision,
      ...changes,
    });
    return created.data;
```

Comment (kamilogorek) [reply src/targets/github.ts:152]: Nitpick: I always prefer early returns for non-happy-path branches, where `else` is redundant. But it's just a visual difference, so I don't mind.

File: src/targets/github.ts [hunk 2]
```diff
@@ -422,6 +334,24 @@ export class GithubTarget extends BaseTarget {
...
   }
 
+  /**
+   * Publishes the release draft.
+   *
+   * @param release_id Release object ID
+   */
+  public async publishReleaseDraft(release_id: number) {
+    if (isDryRun()) {
```
Comment (kamilogorek) [inline src/targets/github.ts:343]: Same here, but your call. We already have this style in the `deleteAsset` function above.

File: src/targets/github.ts [hunk 3]
```diff
@@ -436,31 +366,12 @@ export class GithubTarget extends BaseTarget {
...
-        if (failed.length === 0) {
-          this.logger.debug(`Deleted ${assets.length} assets`);
-        } else {
-          this.logger.debug(
-            'Failed to delete some assets:',
-            failed.map(({ reason }) => reason)
-          );
-        }
-      }
+      throw new Error('Existing assets found for the release draft! Why?');
```
Comment (kamilogorek) [inline src/targets/github.ts:374]: Should we have a way to force the deletion/upload despite assets being somehow there in case of an incident?

**Review by kamilogorek — CHANGES_REQUESTED** [review]
So much code removed 🥰

File: src/targets/github.ts [hunk 4]
```diff
@@ -422,6 +334,24 @@ export class GithubTarget extends BaseTarget {
...
+  /**
+   * Publishes the release draft.
+   *
+   * @param release_id Release object ID
+   */
+  public async publishReleaseDraft(release_id: number) {
+    if (isDryRun()) {
+      this.logger.info(`[dry-run] Not publishing the release draft`);
+    } else {
+      await this.github.repos.updateRelease({
```
Comment (iker-barriocanal) [inline src/targets/github.ts:346]: Is having some protection of this method (like wrapping it in a `try..catch`) overengineering it? [Docs](https://octokit.github.io/rest.js/v18#repos-update-release) don't failure use cases when (e.g. release doesn't exist, an issue with GitHub...), but other methods [throw exceptions](https://github.com/getsentry/craft/pull/328/files#diff-5c75e39457a6946369f245a4d5672bd24e7bb641f645f1ae5412fe4f368cf145R437-R443).

File: src/targets/github.ts (hunk 1 above)
Comment (chadwhitacre) [reply src/targets/github.ts]: Done in d7886d943388383dddec2db271e371d29488d4f8.

File: src/targets/github.ts (hunk 2 above)
Comment (chadwhitacre) [reply src/targets/github.ts:343]: Done in d7886d943388383dddec2db271e371d29488d4f8.

File: src/targets/github.ts (hunk 3 above)
Comment (chadwhitacre) [reply src/targets/github.ts:375]: This is really only here because we _definitely_ needed this check for the previous logic where we were creating a true release object each time. In the draft case, each call to `createRelease` starts a new draft, so this is really more of a sanity check than an expected case. Maybe we should remove it? 🤔

File: src/targets/github.ts [hunk 5]
```diff
@@ -187,56 +130,25 @@ export class GithubTarget extends BaseTarget {
...
-    } else {
+    if (isDryRun()) {
       this.logger.info(`[dry-run] Not creating the release`);
       return {
         id: 0,
         tag_name: tag,
         upload_url: '',
       };
+    } else {
+      const created = await this.github.repos.createRelease({
```
[the remark this answers is not in the document]
Comment (chadwhitacre) [reply src/targets/github.ts]: A new draft release is created each time.

I tested with this patch against d7886d943388383dddec2db271e371d29488d4f8:

```diff
diff --git a/src/targets/github.ts b/src/targets/github.ts
index 65c277e..5617461 100644
--- a/src/targets/github.ts
+++ b/src/targets/github.ts
@@ -139,6 +139,8 @@ export class GithubTarget extends BaseTarget {
       };
     }
 
+    this.logger.warn('CALLING CREATE TWICE');
+
     const created = await this.github.repos.createRelease({
       draft: true,
       name: tag,
@@ -149,6 +151,22 @@ export class GithubTarget extends BaseTarget {
       target_commitish: revision,
       ...changes,
     });
+
+    const second = await this.github.repos.createRelease({
+      draft: true,
+      name: tag,
+      owner: this.githubConfig.owner,
+      prerelease: isPreview,
+      repo: this.githubConfig.repo,
+      tag_name: tag,
+      target_commitish: revision,
+      ...changes,
+    });
<img width="490" alt="Screen Shot 2022-02-08 at 12 39 11 PM" src="https://user-images.githubusercontent.com/134455/153044816-371b2d35-a464-4385-a45a-bf527abf2657.png">

+
+    this.logger.warn('CALLED CREATE TWICE');
+    this.logger.warn(created);
+    this.logger.warn(second);
+
     return created.data;
   }
 
```

Screen Shot 2022-02-08 at 12 39 11 PM

File: src/targets/github.ts (hunk 4 above)
Comment (chadwhitacre) [reply src/targets/github.ts]: If the release doesn't exist we want to bail and find out about it, normal error handling seems fine.

If it's a transient network error I guess we would want to retry, but I'd rather not solve that as a one-off here, we shoudl address that across the board if we want.

File: src/targets/github.ts [hunk 6]
```diff
@@ -187,57 +130,26 @@ export class GithubTarget extends BaseTarget {
...
+        id: 0,
+        tag_name: tag,
+        upload_url: '',
+      };
     }
 
-    const createReleaseParams = {
-      draft: false,
+    const created = await this.github.repos.createRelease({
+      draft: true,
```
Comment (BYK) [inline src/targets/github.ts:143]:
```suggestion
    const { data } = await this.github.repos.createRelease({
      draft: true,
```

Comment (BYK) [reply src/targets/github.ts:143]: Or even:
```suggestion
    return (await this.github.repos.createRelease({
      draft: true,
      ...
    })).data;
```

File: src/targets/github.ts [hunk 7]
```diff
@@ -271,7 +183,7 @@ export class GithubTarget extends BaseTarget {
   ): Promise<boolean> {
     this.logger.debug(`Deleting asset: "${asset.name}"...`);
     if (isDryRun()) {
-      this.logger.info(`[dry-run] Not uploading deleting "${asset.name}"`);
```
Comment (BYK) [inline src/targets/github.ts:274]: lol

File: src/targets/github.ts [hunk 8]
```diff
@@ -187,57 +130,26 @@ export class GithubTarget extends BaseTarget {
...
-      });
-      this.logger.warn(`Found the existing release for tag "${tag}"`);
-      return response.data;
-    } catch (e: any) {
-      if (e.status !== 404) {
-        throw e;
-      }
-      this.logger.debug(`Release for tag "${tag}" not found.`);
+    if (isDryRun()) {
+      this.logger.info(`[dry-run] Not creating the release`);
```
Comment (BYK) [inline src/targets/github.ts:134]: Since this is a draft, I think it might be actually good to create the draft even in dry mode. It doesn't do anything destructive.

File: src/targets/github.ts [hunk 9]
```diff
@@ -422,6 +334,25 @@ export class GithubTarget extends BaseTarget {
     }
   }
 
+  /**
+   * Publishes the release draft.
+   *
+   * @param release_id Release object ID
+   */
+  public async publishReleaseDraft(release_id: number) {
+    if (isDryRun()) {
```
Comment (BYK) [inline src/targets/github.ts:343]: Feels like this pattern can use something like a [decorator](https://www.typescriptlang.org/docs/handbook/decorators.html):
```js
@noopInDryRun
```

File: src/targets/github.ts [hunk 10]
```diff
@@ -422,6 +334,25 @@ export class GithubTarget extends BaseTarget {
...
+      this.logger.info(`[dry-run] Not publishing the release draft`);
+      return;
+    }
+
+    await this.github.repos.updateRelease({
+      owner: this.githubConfig.owner,
+      repo: this.githubConfig.repo,
```
Comment (BYK) [inline src/targets/github.ts:350]:
```suggestion
      ...this.githubConfig,
```

File: src/targets/github.ts [hunk 11]
```diff
@@ -436,31 +367,12 @@ export class GithubTarget extends BaseTarget {
     if (config.changelogPolicy !== ChangelogPolicy.None) {
       changelog = await this.getChangelog(version);
     }
-    const release = await this.getOrCreateRelease(version, revision, changelog);
 
-    const assets = await this.getAssetsForRelease(release.id);
+    const draft = await this.createReleaseDraft(version, revision, changelog);
```
Comment (BYK) [inline src/targets/github.ts:371]:
```suggestion
    const draftRelease = await this.createReleaseDraft(version, revision, changelog);
```

File: src/targets/github.ts [hunk 12]
```diff
@@ -473,8 +385,10 @@ export class GithubTarget extends BaseTarget {
 
     await Promise.all(
       localArtifacts.map(({ path, mimeType }) =>
-        this.uploadAsset(release, path, mimeType)
+        this.uploadAsset(draft, path, mimeType)
       )
     );
+
+    await this.publishReleaseDraft(draft.id);
```
Comment (BYK) [inline src/targets/github.ts:392]: I think this method should accept a `release` object like `uploadAssets` for consistency. (or vice versa)

File: src/targets/upm.ts [hunk 13]
```diff
@@ -145,11 +145,12 @@ export class UpmTarget extends BaseTarget {
         } else {
           await git.push(['origin', 'main']);
           const changes = await this.githubTarget.getChangelog(version);
-          await this.githubTarget.getOrCreateRelease(
+          const draft = await this.githubTarget.createReleaseDraft(
```
Comment (BYK) [inline src/targets/upm.ts:148]:
```suggestion
          const draftRelease = await this.githubTarget.createReleaseDraft(
```

**Review by BYK — APPROVED** [review]
Looks pretty great to me. Does this magically pass all existing tests? Is that how great(!) our test coverage is? 😀

File: src/targets/github.ts (hunk 8 above)
Comment (chadwhitacre) [reply src/targets/github.ts:134]: I don't expect a dry run to have any side effects whatsoever, it should just log. 🐭

File: src/targets/github.ts (hunk 12 above)
Comment (chadwhitacre) [reply src/targets/github.ts]: Done in 7a968f67abeba6dadb462224bba5b1ed4f6fa1dc. 👍

File: src/targets/github.ts (hunk 11 above)
Comment (chadwhitacre) [reply src/targets/github.ts]: Done in 7a968f67abeba6dadb462224bba5b1ed4f6fa1dc. 👍

File: src/targets/github.ts (hunk 10 above)
Comment (chadwhitacre) [reply src/targets/github.ts]: Done in 7a968f67abeba6dadb462224bba5b1ed4f6fa1dc. 👍

**Comment by chadwhitacre** [comment]
Hrm, where did CI go? 🤔

**Comment by chadwhitacre** [comment]
@kamilogorek Could I get a re-review here? 🙏

**Review by kamilogorek — APPROVED** [review]
Just a minor style change, but otherwise looks good!
